### ISSUE TITLE
Why support reconnects?

### ISSUE THREAD

**Issue by sewnie** [altfoxie/drpc#1]
Hi, i'm asking about why on any message sent or read to the Discord IPC, drpc will attempt to reconnect upon failure? If the socket has experienced an error, it is most likely Discord quit. This behavior is present in the popular `rich-go` library, in which i'm finding an alternative for (this project is quite nice).

There is no discussions on this project, so i am asking via an issue.

**Comment by sewnie** [comment]
Additionally, i would like to submit a few features to this project, and i want your thoughts on them as well:
* Support Flatpak and Snap
* Provide a default IPC Client similar to how `net/http` provides a default global top-level HTTP Client.
* Remove reconnects

**Comment by altfoxie** [comment]
Hello! I'm pretty surprised that someone found my project :D

The decision to try reconnecting was exactly due to Discord's quits. For me, it seems quite a common scenario to quit Discord during the application lifecycle (https://github.com/altfoxie/am-rich-presence, for which DRPC was developed).

Thanks, your suggestions look great! The only thing, I just would prefer having the option to disable automatic reconnection (maybe `drpc.New(id, disableReconnect ...bool)`), rather than removing it entirely. Feel free to send a pull request =)

**Comment by sewnie** [comment]
> The decision to try reconnecting was exactly due to Discord's quits.

Could this be due to a missing connection DRPC is supposed to send? that be it a heartbeat or so?

**Comment by altfoxie** [comment]
> > The decision to try reconnecting was exactly due to Discord's quits.
> 
> Could this be due to a missing connection DRPC is supposed to send? that be it a heartbeat or so?

No, I mean situations where a user quits Discord themselves. Overall, connection is stable.

**Comment by sewnie** [comment]
> No, I mean situations where a user quits Discord themselves.

If this is the case, and this behavior is default in the official DiscordSDK, then i see no reason for drpc to have the ability to enable or disable it, as it is most likely a good thing to reconnect rich presence.

**Comment by altfoxie** [comment]
> > No, I mean situations where a user quits Discord themselves.
> 
> If this is the case, and this behavior is default in the official DiscordSDK, then i see no reason for drpc to have the ability to enable or disable it, as it is most likely a good thing to reconnect rich presence.

I don't know if DiscordSDK behaves the same. Since there are no active users of DRPC, I also can't determine if autoreconnect is useful or harmful.

Your other changes look good and I'm happy to merge them when you submit a pull request.

**Comment by sewnie** [comment]
I've looked at the following Discord Rich Presence API implementations:

* [github.com/jewlexx/discord-presence](https://github.com/jewlexx/discord-presence/blob/782c717aa2bfd211ec03d519224c92db42e44f90/src/connection/base.rs#L102)
* [github.com/hugolgst/rich-go](https://github.com/hugolgst/rich-go/blob/4a4fb1d3c362a290243cbb5700836dee449c473b/client/client.go#L59)
* [github.com/sardonicism-04/discord-rich-presence](https://github.com/sardonicism-04/discord-rich-presence/blob/3d035d09ceb01640a6769f2c9c558c95401c56ec/src/ipc_windows.rs#L59)
* [https://github.com/qwertyquerty/pypresence](https://github.com/qwertyquerty/pypresence/blob/31718fb442e563f879160c16e0215c7c1fa16f23/pypresence/baseclient.py#L98C28-L98C28)
* [https://github.com/Lachee/discord-rpc-csharp](https://github.com/Lachee/discord-rpc-csharp/blob/0e08664a68b61e5f7adf341d3946d504e8dcfba2/DiscordRPC/DiscordRpcClient.cs#L446)

and i've noticed (atleast as far as i know and have seen, read with basic language assumptions) that none of them attempt to reconnect, going as far as to return an 'connection closed' error.

So... maybe no reconnect?

**Comment by altfoxie** [comment]
> So... maybe no reconnect?

Since reconnecting was the reason to start this project, I'm only considering the option to disable it. Otherwise, there is no point from DRPC.

**Comment by sewnie** [comment]
> there is no point from DRPC.

I am currently using the rich-go library in my software, but unfortunately it doesn't support Flatpak and doesn't seem to be updated or accept contributions that much.

This project on the other hand is designed pretty good, and i'm willing to contribute that support.
